services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ${PWD}/docker/db:/docker-entrypoint-initdb.d

  matchmaking_service:
    build:
      context: ${PWD}/services/matchmaking
      dockerfile: Dockerfile
    container_name: matchmaking_service
    ports:
      - "8080:8080"
      - "8081:8081"
      - "50051:50051"
    volumes:
      - ${PWD}/services/matchmaking/:/app
      - ${PWD}/services/matchmaking/.air.toml:/app/.air.toml
    depends_on:
      - postgres
    environment:
      - REDIS_CONN=redis:6379
      - DB_CONN=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable&search_path=source
    command: ["go", "test", "-v", "./...", "-cover"]
