// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SourceMatch struct {
	ID         pgtype.UUID
	Region     pgtype.Text
	AverageElo pgtype.Int4
	CreatedAt  pgtype.Timestamp
}

type SourceMatchPlayer struct {
	MatchID pgtype.UUID
	UserID  string
	Team    pgtype.Text
	Elo     pgtype.Int4
}
