name: Matchmaking CI / CD Pipeline

on:
  pull_request:
    paths:
      - "services/matchmaking/**"

jobs:
  matchmaking_test_pipeline:
    name: Matchmaking Test Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Tests
        run: make run-matchmaking-tests
