name: Producer CI / CD Pipeline

on:
  pull_request:
    paths:
      - "services/producer/**"

jobs:
  producer_test_pipeline:
    name: Producer Test Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Tests
        run: make run-producer-tests
